### PR TITLE
add templates of experiments

### PR DESCRIPTION
**Pull request by achoimet**
Still in progress, will come back at you to ask for a reviewing of the experiments week 16.

### CODE REVIEW

**Comment by achoimet** [comment]
One small question @ansgarschulte, in the summary.mdx, what is the difference between intent and motivation ?
It's not crystal clear for me and I tend to overlap things between those two paragraphs.

**Comment by ManuelGerding** [comment]
@achoimet Great question! So this is inspired by how design patterns are described.
The idea is that the **intent** states the problem in a nutshell, which will be addressed by the recipe (1-2 sentences). It also helps for scanning the recipes at the overview page to check whether the addressed problem matches the one a user is facing.

The **motivation** describes a specific scenario where a user may face the problem. It is more elaborative and specific than the intent.

See, for instance, https://hub.steadybit.com/recipe/kubernetes-nodes.node-restart, where the **motivation** describes specific scenarios (node update, spot instance) where the problem of the intent is faced.

**Comment by achoimet** [comment]
Hello @ManuelGerding @ansgarschulte @ReuDa, if you have time today to double check this MR ?

**Comment by ManuelGerding** [comment]
> Hello @ManuelGerding @ansgarschulte @ReuDa, if you have time today to double check this MR ?

I'll take care of this today :-) If anything is right, should I also merge it? Or is it still in WIP as the title is saying?

**Comment by achoimet** [comment]
Ok to merge it

**Review by ManuelGerding — APPROVED** [review]

**Pull request merged**
